### ISSUE TITLE
NullReferenceException when inserting values into AmqpSerializer typeCache dictionary

### ISSUE THREAD

**Issue by mcmellawatt** [Azure/amqpnetlite#111]
One of our tests has exposed what appears to be a threading bug in the AmqpSerializer.  We have multiple threads attempting to encode messages of the same type (int), and occasionally we get a NullReferenceException when inserting values into the typeCache dictionary in AqmpSerializer.cs (line 146).  The AmqpSerializer is a singleton, so It appears the typeCache dictionary is shared and access needs to be synchronized.  Below is a partial stack trace.  Let me know if you need any more details.

```
Result StackTrace:	
at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at Amqp.Serialization.AmqpSerializer.GetOrCompileType(Type type, Boolean describedOnly) in d:\Source\Repos\amqpnetlite-git\src\Serialization\AmqpSerializer.cs:line 146
   at Amqp.Serialization.AmqpSerializer.WriteObject(AmqpSerializer serializer, ByteBuffer buffer, Object graph) in d:\Source\Repos\amqpnetlite-git\src\Serialization\AmqpSerializer.cs:line 127
   at Amqp.Framing.AmqpValue.EncodeValue(ByteBuffer buffer) in d:\Source\Repos\amqpnetlite-git\src\Framing\AmqpValue.cs:line 108
   at Amqp.Types.Described.Encode(ByteBuffer buffer) in d:\Source\Repos\amqpnetlite-git\src\Types\Described.cs:line 33
   at Amqp.Message.WriteToBuffer(ByteBuffer buffer) in d:\Source\Repos\amqpnetlite-git\src\Message.cs:line 244
   at Amqp.Message.Encode(IBufferManager bufferManager, Int32 reservedBytes) in d:\Source\Repos\amqpnetlite-git\src\Message.cs:line 268
   at Amqp.SenderLink.Send(Message message, DeliveryState deliveryState, OutcomeCallback callback, Object state) in d:\Source\Repos\amqpnetlite-git\src\SenderLink.cs:line 152
   at Amqp.SenderLink.Send(Message message, Int32 millisecondsTimeout) in d:\Source\Repos\amqpnetlite-git\src\SenderLink.cs:line 100
Result Message:	
System.NullReferenceException: Object reference not set to an instance of an object.

```

**Comment by xinchen10** [comment]
fixed in 1.1.8
