### ISSUE TITLE
can't connect to arbitrary ip address (net35)

### ISSUE THREAD

**Issue by mbroadst** [Azure/amqpnetlite#18]
I have a sample piece of code like so:

```
string address = "amqp://guest:guest@192.168.1.9:5672";

Connection connection = new Connection(new Address(address));
Session session = new Session(connection);
SenderLink sender = new SenderLink(session, "message-client", "message_processor");

for (int i = 0; i < nMsgs; ++i)
{
    Message message = new Message("hello");
    message.Properties = new Properties() { MessageId = "msg" + i };
    message.ApplicationProperties = new ApplicationProperties();
    message.ApplicationProperties["sn"] = i;
    sender.Send(message);
    Console.WriteLine("Sent message {0} body {1}", message.Properties, message.Body);
}

sender.Close();
session.Close();
connection.Close();
```

and consistently get the following exception:

```
System.Net.Sockets.SocketException (0x80004005): No such host is known
   at System.Net.Dns.InternalGetHostByAddress(IPAddress address, Boolean includeIPv6)
   at System.Net.Dns.GetHostEntry(String hostNameOrAddress)
   at Amqp.TcpTransport.Connect(Connection connection, Address address, Boolean noVerification) in d:\Source\Repos\amqpn
etlite-git\src\Net35\TcpTransport.cs:line 32
   at Amqp.Connection.Connect(SaslProfile saslProfile, Open open) in d:\Source\Repos\amqpnetlite-git\src\Connection.cs:l
ine 265
   at Amqp.Connection..ctor(Address address, SaslProfile saslProfile, Open open, OnOpened onOpened) in d:\Source\Repos\a
mqpnetlite-git\src\Connection.cs:line 120
   at Amqp.Connection..ctor(Address address) in d:\Source\Repos\amqpnetlite-git\src\Connection.cs:line 87
   at ConsoleApplication3.Program.Main(String[] args) in c:\users\mbroadst\documents\visual studio 2010\Projects\Console
Application3\ConsoleApplication3\Program.cs:line 76
```

**Comment by mbroadst** [comment]
it would appear that you need to use `Dns.GetHostAddresses` instead of `Dns.GetHostEntry` [here](https://github.com/Azure/amqpnetlite/blob/master/src/Net35/TcpTransport.cs#L32)

**Comment by ppatierno** [comment]
I tried your code and it works great for me.
Are you using latest version ?

Paolo.

**Comment by mbroadst** [comment]
@ppatierno you must have host records for resolving the IP you're testing with, or 127.0.0.1 which will always resolve. It looks like @xinchen10 fixed this yesterday [here](https://github.com/Azure/amqpnetlite/commit/d28b5987794a9ac9b84da36baf57bc9bb9009bc0), I'm eager to try it out in a point release

**Comment by ppatierno** [comment]
I'm using yesterday latest release ;-)

**Comment by mbroadst** [comment]
@ppatierno I'm fairly certain those commits did not make it into the 1.1.1 release yesterday, note that the release was made 22 hours ago, while those changes occurred 14 hours ago.

**Comment by ppatierno** [comment]
I mean that I synced the repo before executing your test

**Comment by mbroadst** [comment]
Ah, you built from source, I missed that :) Glad to know it's been fixed!

**Comment by mbroadst** [comment]
@xinchen10 I can also confirm this works in master, will close on release

**Comment by mbroadst** [comment]
works in release 1.1.2
