### ISSUE TITLE
Binding to 127.0.0.1 fails on os x

### ISSUE THREAD

**Issue by hsorbo** [Azure/amqpnetlite#225]
On netcoreapp2.0 using `AMQPNetLite.core` `2.0.0-rc`
Binding to 127.0.0.1 in ContainerHosts yields

```
Unhandled Exception: System.AggregateException: One or more errors occurred. (Device not configured) ---> System.Net.Internals.SocketExceptionFactory+ExtendedSocketException: Device not configured
   at System.Net.Dns.InternalGetHostByName(String hostName, Boolean includeIPv6)
   at System.Net.Dns.ResolveCallback(Object context)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Net.Dns.HostResolutionEndHelper(IAsyncResult asyncResult)
   at System.Net.Dns.EndGetHostEntry(IAsyncResult asyncResult)
   at System.Net.Dns.<>c.<GetHostEntryAsync>b__27_1(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Amqp.Listener.ConnectionListener.TcpTransportListener..ctor(ConnectionListener listener, String host, Int32 port)
   at Amqp.Listener.ConnectionListener.Open()
   at Amqp.Listener.ContainerHost.Open()
   at BusTest.Program.Main(String[] args)
```
Changing 127.0.0.1 to localhost resolves this issues.

Example code

```csharp
using System;
using Amqp;
using Amqp.Framing;
using Amqp.Listener;

namespace BusTest
{
    class Program
    {
        static void Main(string[] args)
        {
            var addressUri = new Uri("amqp://guest:guest@127.0.0.1:5672");
            ContainerHost host = new ContainerHost(new Uri[] { addressUri }, null, addressUri.UserInfo);
            host.Open();
        }
    }
}
```

**Comment by hsorbo** [comment]
May be related to this https://github.com/dotnet/corefx/issues/13309

**Comment by xinchen10** [comment]
@hsorbo not sure if it is caused by the corefx issue, but I made a change to the connection listener which I believe should make the code work.
