### ISSUE TITLE
NotSupportedException when using AMQPSerializer on .NET Core 2.0

### ISSUE THREAD

**Issue by cocowalla** [Azure/amqpnetlite#260]
I'm using `AMQPNetLite.Core` and `AMQPNetLite.Serialization`, both at version `2.1.1`.

I'm trying to serialise and send a message using `SenderLink`:

```
var message = new Message
{
    Properties = new Properties { GroupId = this.agentId.ToString("N") },
    BodySection = new AmqpValue<MyRequestMessage>(requestMessage)
};

await sender.SendAsync(message);
```
However, the call to `SendAsync(message)` is throwing `NotSupportedException`:

```
   at Amqp.Serialization.AmqpSerializer.GetOrCompileType(Type type, Boolean describedOnly)
   at Amqp.Serialization.AmqpSerializer.WriteObject(AmqpSerializer serializer, ByteBuffer buffer, Object graph)
   at Amqp.Message.WriteToBuffer(ByteBuffer buffer)
   at Amqp.Message.Encode(IBufferManager bufferManager, Int32 reservedBytes)
   at Amqp.SenderLink.Send(Message message, DeliveryState deliveryState, OutcomeCallback callback, Object state)
   at Amqp.SendTask..ctor(SenderLink link, Message message, DeliveryState state, TimeSpan timeout)
   at Amqp.SenderLink.<SendAsync>d__21.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

`MyRequestMessage `is a simple class with a single Guid property. Any idea what the issue could be?

**Comment by xinchen10** [comment]
Does MyRequestMessage have AmqpContract and AmqpMember attributes defined? Custom types must have the attributes to be serailizable.

**Comment by cocowalla** [comment]
Ah, no, I missed that requirement!

`MyRequestMessage` is in a shared assembly, and I'd rather not have it take a dependency on AMQP.Net Lite - I'd also prefer to keep my classes as POCOs. Is there an alternative to using attributes, such as a way to dynamically mark classes as serialisable?

**Comment by xinchen10** [comment]
Makes sense. Unfortunately the attributes are the only way to make a class serializable right now. This serializer was designed to help application to pass simple objects around using standard AMQP type system. It was not a goal to be a general purpose serializer like json or data contract serializer. But I do see that supporting POCO is important and the serializer should be extensible. I will add support for custom contract resolver that application can implement to support POCOs.

**Comment by cocowalla** [comment]
OK, I didn't realise it wasn't intended to be used for complex types. It's not a big deal for me though, as I can use JSON or MessagePack or whatever (I don't need interoperability with 3rd parties), I just wanted to keep it 'standard' if it was easy to do so.
