### ISSUE TITLE
exception calling ReceiverLink.Receive() and ReceiverLink.ReceiveAsync() in ASP.NET core

### ISSUE THREAD

**Issue by michaelburch** [Azure/amqpnetlite#295]
var session = new Session(connection);
 var filter = new Map();
 filter.Add(new Symbol("com.microsoft:session-filter"), sessionId);
 var rcv = new ReceiverLink(session, "receiver", new Source() { Address = "output/Subscriptions/return", FilterSet = filter }, null);

var responseMsg = rcv.Receive();

Exception:
Amqp.AmqpException: Ticks must be between DateTime.MinValue.Ticks and DateTime.MaxValue.Ticks.
Parameter name: ticks
   at Amqp.ReceiverLink.ReceiveInternal(MessageCallback callback, Int32 timeout) in C:\Users\mqt\repo\amqpnetlite.rel\src\ReceiverLink.cs:line 356
Package versions:
PackageReference Include="Microsoft.AspNetCore.All" Version="2.1.2" 
PackageReference Include="AMQPNetLite.Core" Version="2.1.3" 
PackageReference Include="AMQPNetLite.Serialization" Version="2.1.3"

**Comment by AlexeyEvlampiev** [comment]
Hi,

I am getting same type of error when sending to a topic:

   at Amqp.Link.ThrowIfDetaching(String operation)
   at Amqp.SenderLink.Send(Message message, DeliveryState deliveryState, OutcomeCallback callback, Object state)
   at Amqp.SendTask..ctor(SenderLink link, Message message, DeliveryState state, TimeSpan timeout)
   at Amqp.SenderLink.SendAsync(Message message, TimeSpan timeout)

**Comment by xinchen10** [comment]
Can you receive the same message on full .net framework? This error happens when decoding some DateTime property of the message.

**Comment by michaelburch** [comment]
I'll try to repro on the full framework, but I don't think it's unique to the message. I can specify a value for the receive timeout and the error goes away
