### ISSUE TITLE
Error while deserializing object received over amqp

### ISSUE THREAD

**Issue by GaikwadPratik** [Azure/amqpnetlite#347]
@xinchen10 ,

I am getting an exception attempting to deserialize an object inside message. 

Code is as below: 

```
public class TestRequest
{
     public string firstName { get; set; }
     public string lastName { get; set; }
}
```

```
AmqpSerializer _serializer = new AmqpSerializer();
ByteBuffer _paramsBuffer = new ByteBuffer(1024, true);
_serializer.WriteObject(_paramsBuffer, parameters);
var c = (TestRequest)_serializer.ReadObject<TestRequest>(_paramsBuffer);
```

I also tried:
```
ByteBuffer b = new ByteBuffer(1024, true);
AmqpSerializer.Serialize(b, parameters);
var p = AmqpSerializer.Deserialize<TestRequest>(b);
```

but in both the cases, I receive below exception:

```
Amqp.AmqpException: The format code '192' at frame buffer offset '1' is invalid.
   at Amqp.Serialization.SerializableType.DescribedCompoundType.Initialize(ByteBuffer buffer, Byte formatCode, Int32& size, Int32& count, Int32& encodeWidth, CollectionType& effectiveType)
   at Amqp.Serialization.SerializableType.CollectionType.ReadObject(ByteBuffer buffer)
   at Amqp.Serialization.AmqpSerializer.ReadObject[T,TAs](AmqpSerializer serializer, ByteBuffer buffer)
```

The message is being transmitted to from Qpid C++ broker using `rhea` client and is read using `AmqpNetLite` 

On the same topic, which method is recommended for converting Amqp message to POCO? 
1. ReadObject from AmqpSerializer instance 
2. Deserialize from AmqpSerializer static instance

Please let me know if you need anymore information.

**Comment by xinchen10** [comment]
The serializer by default does not support POCO types. You will need to decorate your class with `AmqpContract` and `AmqpMember` attributes.

But even with that, I am not sure if it will be able to deserialize the message from the rhea client, as it depends on how the rhea client encodes the object in the body. The `AmqpSerializer` expects a described type as the value in the AMQP Value body section.

POCO types can be supported by supplying a custom resolver to the serializer. See Serialization.Poco example for details.

There is no real difference between the instance and the static methods. The instance allows multiple serializers in the same process with different settings.

**Comment by GaikwadPratik** [comment]
I did add those and it still failed with same error. But looking at the POCO example closely I realized that I was missing `EncodingType` on `AmqpContract`. When I set it, It deserialized correctly.

Closing this issue. :)

Thanks for your help!

**Comment by GaikwadPratik** [comment]
Hi @xinchen10 ,

I ran into another issue. 

For deserializing `int` I am getting below error: 

```
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> Amqp.AmqpException: The format code '82' at frame buffer offset '4' is invalid.
   at Amqp.Types.Encoder.ReadLong(ByteBuffer buffer, Byte formatCode)
   at Amqp.Types.Encoder.<>c.<Initialize>b__8_19(ByteBuffer b, Byte c)
   at Amqp.Serialization.SerializableType.DescribedSimpleListType.ReadMemberValue(ByteBuffer buffer, SerializableMember serialiableMember, Object container)
   at Amqp.Serialization.SerializableType.DescribedCompoundType.ReadMembers(ByteBuffer buffer, Object container, Int32& count)
   at Amqp.Serialization.SerializableType.CollectionType.ReadObject(ByteBuffer buffer)
   at Amqp.Serialization.AmqpSerializer.ReadObject[T,TAs](AmqpSerializer serializer, ByteBuffer buffer)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
```

however from [this](https://github.com/Azure/amqpnetlite/blob/master/Examples/PeerToPeer/PeerToPeer.CustomType/Person.cs#L46) example, I should be able to use int. If I change it to `uint` then deserialization works. What am I missing?

`string` and `bool` works correctly

**Comment by xinchen10** [comment]
The producer sends the property as uint so your type has to match what is sent by the producer.

**Comment by GaikwadPratik** [comment]
okay, let me check with the sender(rhea team)... Meanwhile is there anyway to easily understand the exception messages?

 ```The format code '82' at frame buffer offset '4' is invalid```

In case of above example, I don't easily get what is code `82` or offset `4`.
