### ISSUE TITLE
TcpKeepAliveSettings doesn't work on Windows Server 2012 R2 Standard

### ISSUE THREAD

**Issue by Havret** [Azure/amqpnetlite#412]
I’ve done some tests and I can confirm that AmqpNetLite 2.4.0 doesn’t work with TcpKeepAlive enabled on Windows 2012 R2 Standard. The problems occurs only when project targets .NET Framework (I’ve checked .NET Framework 4.6.2, 4.7.2, and 4.8), but doesn’t occur with .NET Core (I’ve checked .NET Core 3.1). 

The problem doesn’t occur on Windows 10 irrespectively of the runtime.

**Exception:**
```
Unhandled Exception: System.Net.Sockets.SocketException: An unknown, invalid, or unsupported option or level was specifi
ed in a getsockopt or setsockopt call
   at System.Net.Sockets.Socket.SetSocketOption(SocketOptionLevel optionLevel, SocketOptionName optionName, Int32 option
Value, Boolean silent)
   at System.Net.Sockets.Socket.SetSocketOption(SocketOptionLevel optionLevel, SocketOptionName optionName, Int32 option
Value)
   at Amqp.TcpSettings.Configure(Socket socket)
   at Amqp.TcpTransport.<ConnectAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Amqp.ConnectionFactory.<CreateAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at TcpKeepAliveSettings.Program.<Main>d__0.MoveNext() in C:\Users\Administrator\Downloads\TcpKeepAliveSettings-master
\TcpKeepAliveSettings\Program.cs:line 18
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at TcpKeepAliveSettings.Program.<Main>(String[] args)
```

**Repro:**
```
using System;
using System.Threading.Tasks;
using Amqp;

namespace TcpKeepAliveSettings
{
    class Program
    {
        static async Task Main(string[] args)
        {
            var address = new Address("amqp://guest:guest@localhost:5672");
            var connectionFactory = new ConnectionFactory();
            connectionFactory.TCP.KeepAlive = new Amqp.TcpKeepAliveSettings()
            {
                KeepAliveInterval = 1000,
                KeepAliveTime = 1000
            };
            await connectionFactory.CreateAsync(address);
            var connection = new Connection(address);
            var session = new Session(connection);

            var message = new Message("Hello AMQP!");
            var sender = new SenderLink(session, "sender-link", "q1");
            sender.Send(message);
            Console.WriteLine("Sent Hello AMQP!");

            sender.Close();
            session.Close();
            connection.Close();
        }
    }
}
```

**Comment by xinchen10** [comment]
Tested the code (targeting .Net framework 4.6.2) on Windows Server 2012 R2 Datacenter Version 6.3.9600. It worked without issues.
