### ISSUE TITLE
Amqp.AmqpException: The format code '60' at frame buffer offset '23' is invalid.

### ISSUE THREAD

**Issue by torsannes** [Azure/amqpnetlite#457]
Hello,

I am getting the error above when receiving a message on Amazon MQ (that is the same as Active MQ). The message has been inserted on the queue using Java and Spring Boot. 
Can you based on the tracelog below pinpoint any problems with the input, or with the AmqpNetLite library?

Best regards,
Tor Sannes
```
Receiver connected to broker.
[01:11:05.596] SEND 0000002502000000005313C018095201700000080070FFFFFFFD7000003FFF434352C84042
[01:11:05.596] RECV 0000003102000000005312C0240AA106696D706F7274434250025000005328C00901A106696D706F727400532945404243
[01:11:05.599] RECV 0000228D02000000005314C008054343A001004342003C003F0078006D006C002000760065007200730069006F006E003D00220031002E0030002200200065006E0063006F00640069006E0067003D0022005500540046002D003100360022003F003E003C005200650071007500650073007400200078006D006C006E0073003A007800730069003D00220068007400740070003A002F002F007700770077002E00770033002E006F00720067002F0032003000300031002F0058004D004C0053006300680065006D0061002D0069006E007300740061006E00630065002200200078006D006C006E0073003A007800730064003D00220068007400740070003A002F002F007700770077002E00770033002E006F00720067002F0032003000300031002F0058004D004C0053006300680065006D0061002200200078006D006C006E0073003D00220068007400740070003A002F002F007700770077002E0070006F00770065006C002E0063006F006D002F0053006D0045002F0041004D00510050006D006500730073006100670065005400790070006500730022003E003C004D00650073007300610067006500490064003E00650031003100610030003700340032002D0035003000620064002D0034003300300064002D0062003900370039002D003400390063006100660061006600310065003000640065003C002F004D00650073007300610067006500490064003E003C004D00650073007300610067006500560065007200730069006F006E003E0031002E0030002E0030002E0030003C002F004D00650073007300610067006500560065007200730069006F006E003E003C0049006E0070007500740073003E003C00540069006D00650073006500720069006500730050006F0069006E00740073003E003C0050006F0069006E0074007300200050006100740068003D0022004D006F00640065006C002F0045006E0065006C002F004D006500730068002F00220020005300650061007200630068003D0022002A005B002E0054007900700065003D0054006800650072006D0061006C0055006E006900740049006D0070006F00720074004400610074006100260061006D0070003B00260061006D0070003B002E004E0061006D0065003D002600710075006F0074003B0052004F0031002600710075006F0074003B005D002E00500072006F00640075006300740069006F006E004D006100780022002000440065006C007400610054003D002200500054003100480022003E003C005300650067006D0065006E00740073003E003C005300650067006D0065006E0074002000530074006100720074003D00220032003000320031002D00300033002D00310037005400320033003A00300030003A00300030005A002200200045006E0064003D00220032003000320031002D00300033002D00320030005400320033003A00300030003A00300030005A0022003E003C0050006F0069006E0074002000540069006D0065007300740061006D0070003D00220032003000320031002D00300033002D00310037005400320033003A00300030003A00300030005A0022002000560061006C00750065003D00220031003200350022002F003E003C0050006F0069006E0074002000540069006D0065007300740061006D0070003D00220032003000320031002D00300033002D00310038005400300030003A00300030003A00300030005A0022002000560061006C00750065003D00220031003200350022002F003E003C0050006F0069006E0074002000540069006D0065007300740061006D0070003D00220032003000320031002D00300033002D00310038005400300031003A00300030003A00300030005A0022002000560061006C00750065003D00220031003200350022002F003E003C0050006F0069006E0074002000540069006D0065007300740061006D0070003D00220032003000320031002D00300033002D00310038005400300032003A00300030003A00300030005A0022002000560061006C00750065003D00220031003200350022002F003E003C0050006F0069006E0074002000540069006D0065007300740061006D0070003D00220032003000320031002D00300033002D00310038005400300033003A00300030003A00300030005A0022002000560061006C00750065003D00220031003200350022002F003E003C0050006F0069006E0074002000540069006D0065007300740061006D0070003D00220032003000320031002D00300033002D00310038005400300034003A00300030003A00300030005A0022002000560061006C00750065003D00220031003200350022002F003E003C0050006F0069006E0074002000540069006D0065007300740061006D0070003D00220032003000320031002D00300033002D00310038005400300035003A00300030003A00300030005A0022002000560061006C00750065003D00220031003200350022002F003E003C0050006F0069006E0074002000540069006D0065007300740061006D0070003D00220032003000320031002D00300033002D00310038005400300036003A00300030003A00300030005A0022002000560061006C00750065003D00220031003200350022002F003E003C0050006F0069006E0074002000540069006D0065007300740061006D0070003D00220032003000320031002D00300033002D00310038005400300037003A00300030003A00300030005A0022002000560061006C00750065003D00220031003200350022002F003E003C0050006F0069006E0074002000540069006D0065007300740061006D0070003D00220032003000320031002D00300033002D00310038005400300038003A00300030003A00300030005A0022002000560061006C00750065003D00220031003200350022002F003E003C0050006F0069006E0074002000540069006D0065007300740061006D0070003D00220032003000320031002D00300033002D00310038005400300039003A00300030003A00300030005A0022002000560061006C00750065003D00220031003200350022002F003E003C0050006F0069006E0074002000540069006D0065007300740061006D0070003D00220032003000320031002D00300033002D00310038005400310030003A00300030003A00300030005A0022002000560061006C00750065003D00220031003200350022002F003E003C0050006F0069006E0074002000540069006D0065007300740061006D0070003D00220032003000320031002D00300033002D00310038005400310031003A00300030003A00300030005A0022002000560061006C00750065003D00220031003200350022002F003E003C0050006F0069006E0074002000540069006D0065007300740061006D0070003D00220032003000320031002D00300033002D00310038005400310032003A00300030003A00300030005A0022002000560061006C00750065003D00220031003200350022002F003E003C0050006F0069006E0074002000540069006D0065007300740061006D0070003D00220032003000320031002D00300033002D00310038005400310033003A00300030003A00300030005A0022002000560061006C00750065003D00220031003200350022002F003E003C0050006F0069006E0074002000540069006D0065007300740061006D0070003D00220032003000320031002D00300033002D00310038005400310034003A00300030003A00300030005A0022002000560061006C00750065003D00220031003200350022002F003E003C0050006F0069006E0074002000540069006D0065007300740061006D0070003D00220032003000320031002D00300033002D00310038005400310035003A00300030003A00300030005A0022002000560061006C00750065003D00220031003200350022002F003E003C0050006F0069006E0074002000540069006D0065007300740061006D0070003D00220032003000320031002D00300033002D00310038005400310036003A00300030003A00300030005A0022002000560061006C00750065003D00220031003200350022002F003E003C0050006F0069006E0074002000540069006D0065007300740061006D0070003D00220032003000320031002D00300033002D00310038005400310037003A00300030003A00300030005A0022002000560061006C00750065003D00220031003200350022002F003E003C0050006F0069006E0074002000540069006D0065007300740061006D0070003D00220032003000320031002D00300033002D00310038005400310038003A00300030003A00300030005A0022002000560061006C00750065003D00220031003200350022002F003E003C0050006F0069006E0074002000540069006D0065007300740061006D0070003D00220032003000320031002D00300033002D00310038005400310039003A00300030003A00300030005A0022002000560061006C00750065003D00220031003200350022002F003E003C0050006F0069006E0074002000540069006D0065007300740061006D0070003D00220032003000320031002D00300033002D00310038005400320030003A00300030003A00300030005A0022002000560061006C00750065003D00220031003200350022002F003E003C0050006F0069006E0074002000540069006D0065007300740061006D0070003D00220032003000320031002D00300033002D00310038005400320031003A00300030003A00300030005A0022002000560061006C00750065003D00220031003200350022002F003E003C0050006F0069006E0074002000540069006D0065007300740061006D0070003D00220032003000320031002D00300033002D00310038005400320032003A00300030003A00300030005A0022002000560061006C00750065003D00220031003200350022002F003E003C0050006F0069006E0074002000540069006D0065007300740061006D0070003D00220032003000320031002D00300033002D00310038005400320033003A00300030003A00300030005A0022002000560061006C00750065003D00220031003200350022002F003E003C0050006F0069006E0074002000540069006D0065007300740061006D0070003D00220032003000320031002D00300033002D00310039005400300030003A00300030003A00300030005A0022002000560061006C00750065003D00220031003200350022002F003E003C0050006F0069006E0074002000540069006D0065007300740061006D0070003D00220032003000320031002D00300033002D00310039005400300031003A00300030003A00300030005A0022002000560061006C00750065003D00220031003200350022002F003E003C0050006F0069006E0074002000540069006D0065007300740061006D0070003D00220032003000320031002D00300033002D00310039005400300032003A00300030003A00300030005A0022002000560061006C00750065003D00220031003200350022002F003E003C0050006F0069006E0074002000540069006D0065007300740061006D0070003D00220032003000320031002D00300033002D00310039005400300033003A00300030003A00300030005A0022002000560061006C00750065003D00220031003200350022002F003E003C0050006F0069006E0074002000540069006D0065007300740061006D0070003D00220032003000320031002D00300033002D00310039005400300034003A00300030003A00300030005A0022002000560061006C00750065003D00220031003200350022002F003E003C0050006F0069006E0074002000540069006D0065007300740061006D0070003D00220032003000320031002D00300033002D00310039005400300035003A00300030003A00300030005A0022002000560061006C00750065003D00220031003200350022002F003E003C0050006F0069006E0074002000540069006D0065007300740061006D0070003D00220032003000320031002D00300033002D00310039005400300036003A00300030003A00300030005A0022002000560061006C00750065003D00220031003200350022002F003E003C0050006F0069006E0074002000540069006D0065007300740061006D0070003D00220032003000320031002D00300033002D00310039005400300037003A00300030003A00300030005A0022002000560061006C00750065003D00220031003200350022002F003E003C0050006F0069006E0074002000540069006D0065007300740061006D0070003D00220032003000320031002D00300033002D00310039005400300038003A00300030003A00300030005A0022002000560061006C00750065003D00220031003200350022002F003E003C0050006F0069006E0074002000540069006D0065007300740061006D0070003D00220032003000320031002D00300033002D00310039005400300039003A00300030003A00300030005A0022002000560061006C00750065003D00220031003200350022002F003E003C0050006F0069006E0074002000540069006D0065007300740061006D0070003D00220032003000320031002D00300033002D00310039005400310030003A00300030003A00300030005A0022002000560061006C00750065003D00220031003200350022002F003E003C0050006F0069006E0074002000540069006D0065007300740061006D0070003D00220032003000320031002D00300033002D00310039005400310031003A00300030003A00300030005A0022002000560061006C00750065003D00220031003200350022002F003E003C0050006F0069006E0074002000540069006D0065007300740061006D0070003D00220032003000320031002D00300033002D00310039005400310032003A00300030003A00300030005A0022002000560061006C00750065003D00220031003200350022002F003E003C0050006F0069006E0074002000540069006D0065007300740061006D0070003D00220032003000320031002D00300033002D00310039005400310033003A00300030003A00300030005A0022002000560061006C00750065003D00220031003200350022002F003E003C0050006F0069006E0074002000540069006D0065007300740061006D0070003D00220032003000320031002D00300033002D00310039005400310034003A00300030003A00300030005A0022002000560061006C00750065003D00220031003200350022002F003E003C0050006F0069006E0074002000540069006D0065007300740061006D0070003D00220032003000320031002D00300033002D00310039005400310035003A00300030003A00300030005A0022002000560061006C00750065003D00220031003200350022002F003E003C0050006F0069006E0074002000540069006D0065007300740061006D0070003D00220032003000320031002D00300033002D00310039005400310036003A00300030003A00300030005A0022002000560061006C00750065003D00220031003200350022002F003E003C0050006F0069006E0074002000540069006D0065007300740061006D0070003D00220032003000320031002D00300033002D00310039005400310037003A00300030003A00300030005A0022002000560061006C00750065003D00220031003200350022002F003E003C0050006F0069006E0074002000540069006D0065007300740061006D0070003D00220032003000320031002D00300033002D00310039005400310038003A00300030003A00300030005A0022002000560061006C00750065003D00220031003200350022002F003E003C0050006F0069006E0074002000540069006D0065007300740061006D0070003D00220032003000320031002D00300033002D00310039005400310039003A00300030003A00300030005A0022002000560061006C00750065003D00220031003200350022002F003E003C0050006F0069006E0074002000540069006D0065007300740061006D0070003D00220032003000320031002D00300033002D00310039005400320030003A00300030003A00300030005A0022002000560061006C00750065003D00220031003200350022002F003E003C0050006F0069006E0074002000540069006D0065007300740061006D0070003D00220032003000320031002D00300033002D00310039005400320031003A00300030003A00300030005A0022002000560061006C00750065003D00220031003200350022002F003E003C0050006F0069006E0074002000540069006D0065007300740061006D0070003D00220032003000320031002D00300033002D00310039005400320032003A00300030003A00300030005A0022002000560061006C00750065003D00220031003200350022002F003E003C0050006F0069006E0074002000540069006D0065007300740061006D0070003D00220032003000320031002D00300033002D00310039005400320033003A00300030003A00300030005A0022002000560061006C00750065003D00220031003200350022002F003E003C0050006F0069006E0074002000540069006D0065007300740061006D0070003D00220032003000320031002D00300033002D00320030005400300030003A00300030003A00300030005A0022002000560061006C00750065003D00220031003200350022002F003E003C0050006F0069006E0074002000540069006D0065007300740061006D0070003D00220032003000320031002D00300033002D00320030005400300031003A00300030003A00300030005A0022002000560061006C00750065003D00220031003200350022002F003E003C0050006F0069006E0074002000540069006D0065007300740061006D0070003D00220032003000320031002D00300033002D00320030005400300032003A00300030003A00300030005A0022002000560061006C00750065003D00220031003200350022002F003E003C0050006F0069006E0074002000540069006D0065007300740061006D0070003D00220032003000320031002D00300033002D00320030005400300033003A00300030003A00300030005A0022002000560061006C00750065003D00220031003200350022002F003E003C0050006F0069006E0074002000540069006D0065007300740061006D0070003D00220032003000320031002D00300033002D00320030005400300034003A00300030003A00300030005A0022002000560061006C00750065003D00220031003200350022002F003E003C0050006F0069006E0074002000540069006D0065007300740061006D0070003D00220032003000320031002D00300033002D00320030005400300035003A00300030003A00300030005A0022002000560061006C00750065003D00220031003200350022002F003E003C0050006F0069006E0074002000540069006D0065007300740061006D0070003D00220032003000320031002D00300033002D00320030005400300036003A00300030003A00300030005A0022002000560061006C00750065003D00220031003200350022002F003E003C0050006F0069006E0074002000540069006D0065007300740061006D0070003D00220032003000320031002D00300033002D00320030005400300037003A00300030003A00300030005A0022002000560061006C00750065003D00220031003200350022002F003E003C0050006F0069006E0074002000540069006D0065007300740061006D0070003D00220032003000320031002D00300033002D00320030005400300038003A00300030003A00300030005A0022002000560061006C00750065003D00220031003200350022002F003E003C0050006F0069006E0074002000540069006D0065007300740061006D0070003D00220032003000320031002D00300033002D00320030005400300039003A00300030003A00300030005A0022002000560061006C00750065003D00220031003200350022002F003E003C0050006F0069006E0074002000540069006D0065007300740061006D0070003D00220032003000320031002D00300033002D00320030005400310030003A00300030003A00300030005A0022002000560061006C00750065003D00220031003200350022002F003E003C0050006F0069006E0074002000540069006D0065007300740061006D0070003D00220032003000320031002D00300033002D00320030005400310031003A00300030003A00300030005A0022002000560061006C00750065003D00220031003200350022002F003E003C0050006F0069006E0074002000540069006D0065007300740061006D0070003D00220032003000320031002D00300033002D00320030005400310032003A00300030003A00300030005A0022002000560061006C00750065003D00220031003200350022002F003E003C0050006F0069006E0074002000540069006D0065007300740061006D0070003D00220032003000320031002D00300033002D00320030005400310033003A00300030003A00300030005A0022002000560061006C00750065003D00220031003200350022002F003E003C0050006F0069006E0074002000540069006D0065007300740061006D0070003D00220032003000320031002D00300033002D00320030005400310034003A00300030003A00300030005A0022002000560061006C00750065003D00220031003200350022002F003E003C0050006F0069006E0074002000540069006D0065007300740061006D0070003D00220032003000320031002D00300033002D00320030005400310035003A00300030003A00300030005A0022002000560061006C00750065003D00220031003200350022002F003E003C0050006F0069006E0074002000540069006D0065007300740061006D0070003D00220032003000320031002D00300033002D00320030005400310036003A00300030003A00300030005A0022002000560061006C00750065003D00220031003200350022002F003E003C0050006F0069006E0074002000540069006D0065007300740061006D0070003D00220032003000320031002D00300033002D00320030005400310037003A00300030003A00300030005A0022002000560061006C00750065003D00220031003200350022002F003E003C0050006F0069006E0074002000540069006D0065007300740061006D0070003D00220032003000320031002D00300033002D00320030005400310038003A00300030003A00300030005A0022002000560061006C00750065003D00220031003200350022002F003E003C0050006F0069006E0074002000540069006D0065007300740061006D0070003D00220032003000320031002D00300033002D00320030005400310039003A00300030003A00300030005A0022002000560061006C00750065003D00220031003200350022002F003E003C0050006F0069006E0074002000540069006D0065007300740061006D0070003D00220032003000320031002D00300033002D00320030005400320030003A00300030003A00300030005A0022002000560061006C00750065003D00220031003200350022002F003E003C0050006F0069006E0074002000540069006D0065007300740061006D0070003D00220032003000320031002D00300033002D00320030005400320031003A00300030003A00300030005A0022002000560061006C00750065003D00220031003200350022002F003E003C0050006F0069006E0074002000540069006D0065007300740061006D0070003D00220032003000320031002D00300033002D00320030005400320032003A00300030003A00300030005A0022002000560061006C00750065003D00220031003200350022002F003E003C002F005300650067006D0065006E0074003E003C002F005300650067006D0065006E00740073003E003C002F0050006F0069006E00740073003E003C002F00540069006D00650073006500720069006500730050006F0069006E00740073003E003C002F0049006E0070007500740073003E003C002F0052006500710075006500730074003E
[01:11:05.755] SEND 0000006D02000000005318C0600100531DC05A02A311616D71703A6465636F64652D6572726F72A14454686520666F726D617420636F64652027363027206174206672616D6520627566666572206F6666736574202732332720697320696E76616C6964202D20706F733D312E
Exception: Amqp.AmqpException: The format code '60' at frame buffer offset '23' is invalid.
   at Amqp.ReceiverLink.ReceiveInternal(MessageCallback callback, Int32 timeout)
   at Amqp.ReceiverLink.Receive(TimeSpan timeout)
   at AmqpTestCore.Program.Receive(ReceiverLink& receiver, Session session, String linkName, String linkAddress, String directory, Boolean debug, Boolean stopWhenEmpty)
```

**Comment by xinchen10** [comment]
The message payload in the transfer frame is invalid.
```
frame header: 0000228D02000000
transfer: 005314 C008054343A001004342
message: 003C003F0078006D006C002000760065007200730069006F
```

The second byte 0x3c in the message payload is not a valid format code for any of the defined sections. It must be one of the following.
```
header: 0x70
delivery-annotations: 0x71
message-annotations: 0x72
properties: 0x73
application-properties: 0x74
data: 0x75
sequence: 0x76
value: 0x77
footer: 0x78
```
