### ISSUE TITLE
error deserializing SimpleMap type

### ISSUE THREAD

**Issue by mbroadst** [Azure/amqpnetlite#86]
Hi, I have the following type I'm trying to deserialize from a node producer:

```
        [AmqpContract(Encoding = EncodingType.SimpleMap)]
        class DisplayMessageRequest
        {
            [AmqpMember]
            public string title { get; set; }

            [AmqpMember]
            public string message { get; set; }
        }
```

When I try deserializing it with the following code:
```
DisplayMessageRequest r = request.GetBody<DisplayMessageRequest>();
```

I get the following exception (with some debug information above the exception):
```
2016-01-29 13:37:10.4246 [Debug] executing requested action: MESSAGE
2016-01-29 13:37:10.4406 [Debug] type: Amqp.Types.Map, body: [message:test message,title:test title]
2016-01-29 13:37:10.4558 [Error] Agent.Modules.Host+DisplayMessageAction.Agent.Actions.IAgentAction.Execute System.InvalidOperationException: buffer too small
   at Amqp.ByteBuffer.Validate(Boolean write, Int32 dataSize) in d:\Source\Repos\amqpnetlite-git\src\ByteBuffer.cs:line 158
   at Amqp.AmqpBitConverter.ReadByte(ByteBuffer buffer) in d:\Source\Repos\amqpnetlite-git\src\AmqpBitConverter.cs:line 44
   at Amqp.Serialization.SerializableType.CollectionType.ReadObject(ByteBuffer buffer) in d:\Source\Repos\amqpnetlite-git\src\Serialization\SerializableType.cs:line 356

   at Amqp.Serialization.AmqpSerializer.ReadObject[T,TAs](AmqpSerializer serializer, ByteBuffer buffer) in d:\Source\Repos\amqpnetlite-git\src\Serialization\AmqpSerializer.cs:line 135
   at Amqp.Serialization.AmqpSerializer.Deserialize[T](ByteBuffer buffer) in d:\Source\Repos\amqpnetlite-git\src\Serialization\AmqpSerializer.cs:line 66
   at Amqp.Framing.AmqpValue.GetValue[T]() in d:\Source\Repos\amqpnetlite-git\src\Framing\AmqpValue.cs:line 95
   at Amqp.Message.GetBody[T]() in d:\Source\Repos\amqpnetlite-git\src\Message.cs:line 119
   at Agent.Modules.Host.DisplayMessageAction.Agent.Actions.IAgentAction.Execute(SenderLink sender, ReceiverLink receiver, Message request) in C:\Users\mbroadst\Development\hive-agent\Agent\Modules\Host.cs:line 221System.InvalidOperationException: buffer too small
   at Amqp.ByteBuffer.Validate(Boolean write, Int32 dataSize) in d:\Source\Repos\amqpnetlite-git\src\ByteBuffer.cs:line 158
   at Amqp.AmqpBitConverter.ReadByte(ByteBuffer buffer) in d:\Source\Repos\amqpnetlite-git\src\AmqpBitConverter.cs:line 44
   at Amqp.Serialization.SerializableType.CollectionType.ReadObject(ByteBuffer buffer) in d:\Source\Repos\amqpnetlite-git\src\Serialization\SerializableType.cs:line 356

   at Amqp.Serialization.AmqpSerializer.ReadObject[T,TAs](AmqpSerializer serializer, ByteBuffer buffer) in d:\Source\Repos\amqpnetlite-git\src\Serialization\AmqpSerializer.cs:line 135
   at Amqp.Serialization.AmqpSerializer.Deserialize[T](ByteBuffer buffer) in d:\Source\Repos\amqpnetlite-git\src\Serialization\AmqpSerializer.cs:line 66
   at Amqp.Framing.AmqpValue.GetValue[T]() in d:\Source\Repos\amqpnetlite-git\src\Framing\AmqpValue.cs:line 95
   at Amqp.Message.GetBody[T]() in d:\Source\Repos\amqpnetlite-git\src\Message.cs:line 119
   at Agent.Modules.Host.DisplayMessageAction.Agent.Actions.IAgentAction.Execute(SenderLink sender, ReceiverLink receiver, Message request) in C:\Users\mbroadst\Development\hive-agent\Agent\Modules\Host.cs:line 221    at Amqp.ByteBuffer.Validate(Boolean write, Int32 dataSize) in d:\Source\Repos\amqpnetlite-git\src\ByteBuffer.cs:line 158
   at Amqp.AmqpBitConverter.ReadByte(ByteBuffer buffer) in d:\Source\Repos\amqpnetlite-git\src\AmqpBitConverter.cs:line 44
   at Amqp.Serialization.SerializableType.CollectionType.ReadObject(ByteBuffer buffer) in d:\Source\Repos\amqpnetlite-git\src\Serialization\SerializableType.cs:line 356

   at Amqp.Serialization.AmqpSerializer.ReadObject[T,TAs](AmqpSerializer serializer, ByteBuffer buffer) in d:\Source\Repos\amqpnetlite-git\src\Serialization\AmqpSerializer.cs:line 135
   at Amqp.Serialization.AmqpSerializer.Deserialize[T](ByteBuffer buffer) in d:\Source\Repos\amqpnetlite-git\src\Serialization\AmqpSerializer.cs:line 66
   at Amqp.Framing.AmqpValue.GetValue[T]() in d:\Source\Repos\amqpnetlite-git\src\Framing\AmqpValue.cs:line 95
   at Amqp.Message.GetBody[T]() in d:\Source\Repos\amqpnetlite-git\src\Message.cs:line 119
   at Agent.Modules.Host.DisplayMessageAction.Agent.Actions.IAgentAction.Execute(SenderLink sender, ReceiverLink receiver, Message request) in C:\Users\mbroadst\Development\hive-agent\Agent\Modules\Host.cs:line 221
```

**Comment by mbroadst** [comment]
Well this is quite strange, the error was because I was printing out the content of the message `Body` before running the action. I'm using NLog, and this line:

```
logger.Debug("message body: {0}", message.Body);
```

I guess actually consumed the body data?

**Comment by xinchen10** [comment]
@mbroadst Accessing message.Body will consume the buffer. We could rewind the buffer in GetBody call.

**Comment by mbroadst** [comment]
@xinchen10 I think maybe its enough to document that behavior, its not mentioned in the source. By the way, are there compiled docs anywhere online?

**Comment by xinchen10** [comment]
@mbroadst I decided to rewind the buffer before deserializing the object. Now your test should work with that change. The compiled XML doc is available only in the latest NuGet package. I wanted to write wiki pages on major areas (e.g. protocol, serialization, listener, etc) but haven't got time to finish all of them.

**Comment by mbroadst** [comment]
@xinchen10 great! thanks for the quick work.
